[project]
authors = ["Ubuntu"]
entry = "main.sw"
license = "Apache-2.0"
name = "voting-contract"

[dependencies]
ownership = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.13.0" }
src_5 = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.1.0" }
